order:
  expire-minutes: 15

spring:
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  security:
    enabled: false  # actuator security 끄기
