spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/json_store}
    username: ${DB_USERNAME:json}
    password: ${DB_PASSWORD:jsonpw}

  jwt:
    secret-key: "${SECRET_KEY}"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#        show_sql: true
#        use_sql_comments: true
    open-in-view: false

  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${REGION}
      s3:
        bucket: ${BUCKET_NAME}

  elasticsearch:
    connection-timeout: 3s
    uris: ${ELASTICSEARCH_HOST:localhost}


logging:
  level:
#    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  config: classpath:logback-dev.xml

#로컬에서 가져올 때 (CI)
fcm:
  credentials:
    file: classpath:firebaseAccessKey.json

external:
  api:
    address:
      key: ${API_KEY}

tosspayments:
  api-base: ${TOSSPAYMENTS_API_BASE:https://api.tosspayments.com}
  api-secret: ${TOSSPAYMENTS_API_SECRET:test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6}

decorator:
  datasource:
    enabled: true
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
  